# Generated by Django 4.2.2 on 2023-07-26 15:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_registration_delete_customer'),
    ]

    operations = [
        migrations.RenameField(
            model_name='registration',
            old_name='fname',
            new_name='f_name',
        ),
        migrations.RenameField(
            model_name='registration',
            old_name='lname',
            new_name='l_name',
        ),
        migrations.RenameField(
            model_name='registration',
            old_name='email',
            new_name='r_email',
        ),
        migrations.RenameField(
            model_name='registration',
            old_name='phone',
            new_name='r_phone',
        ),
    ]
